services:
  - type: web
    name: ramirez-bonjoshpaolo-lavalust
    runtime: docker
    repo: https://github.com/ramirez-bonjoshpaolo-hub/ramirez-bonjoshpaolo-lavalust
    branch: main
    plan: free
    region: singapore
    autoDeployTrigger: commit
    healthCheckPath: /
